#!/bin/bash

PATH=${PATH}:.
PS="-l -r -u -ul -ur -uc3 -urc3 -ui  -uirc3 -uirc10 -ukrc3 -uikrc3 -uimrc3" 

ST=${RANDOM}

#echo '../tests/r3_50_200_1.cnf'  | while read f 
FAIL=false
ls -rS ../tests/*.cnf | while read f 
do 
  N=`basename ${f}`
  echo $N
  TEST_STR=""
  for P in ${PS} ""; do
    OF=/tmp/${N}.${P}.${ST}.out
    ../src/minibones ${P}  $f 2>/dev/null >${OF}
    TEST_STR=${TEST_STR}" v "${OF} 
  done
  bbcmp.py ${TEST_STR}

  if [ $? != 0 ]; then
    FAIL=true
  fi 
done

if $FAIL; then
  echo FAIL
else
  echo OK
fi
